#!/bin/bash

echo "🚀 FVNIX 網站快速部署到 Vercel"
echo "================================"
echo ""
echo "請按照以下步驟操作："
echo ""
echo "1️⃣ 安裝 Vercel CLI（如果還沒安裝）："
echo "   npm install -g vercel"
echo ""
echo "2️⃣ 登錄 Vercel："
echo "   vercel login"
echo "   （會在瀏覽器中打開，完成登錄）"
echo ""
echo "3️⃣ 進入項目目錄："
echo "   cd /home/user/webapp/fvnix-site"
echo ""
echo "4️⃣ 部署到測試環境："
echo "   vercel"
echo ""
echo "5️⃣ 部署到生產環境："
echo "   vercel --prod"
echo ""
echo "================================"
echo ""
echo "📋 在部署過程中會詢問："
echo ""
echo "? Set up and deploy \"~/webapp/fvnix-site\"?"
echo "  → 輸入: y"
echo ""
echo "? Which scope do you want to deploy to?"
echo "  → 選擇您的賬號"
echo ""
echo "? Link to existing project?"
echo "  → 輸入: n (第一次) 或 y (如果已創建)"
echo ""
echo "? What's your project's name?"
echo "  → 輸入: fvnix-site"
echo ""
echo "? In which directory is your code located?"
echo "  → 按 Enter (使用 ./)"
echo ""
echo "✅ 完成後會顯示部署 URL！"
echo ""

# 檢查是否已安裝 vercel
if command -v vercel &> /dev/null; then
    echo "✅ Vercel CLI 已安裝"
    echo ""
    echo "執行以下命令開始部署："
    echo "  vercel"
else
    echo "⚠️  Vercel CLI 未安裝"
    echo ""
    echo "請先執行："
    echo "  npm install -g vercel"
fi
